if(localStorage.getItem("active_user")){
    if(localStorage.getItem("type")=="hospital"){
        $("#username").text(JSON.parse(localStorage.getItem("active_user")).username)
        $("#name").text(JSON.parse(localStorage.getItem("active_user")).username)
    }
    else{
        location.href="../../404/404.html"
    }
}
else{
    location.href="../../404/404.html"
}
$("#logout").click(()=>{
    localStorage.clear()
    location.href="../../User_dashboard/Login/login.html"
})